### PR TITLE
feat: Cozy-bar v3.0.1 :arrow_up:

### PR DESCRIPTION
**Pull request by gregorylegarec**
Update Cozy-Bar to v3.0.1 and add permission for fetching `settings/context`.
The goal is to be able to fetch Coming Soon app and prepare the landing of _Claudy_, our friendly little cloud.

### CODE REVIEW

**Comment by jacquarg** [comment]
Hi @gregorylegarec,
Sorry, I forgot about this PR ! 
Do you close it because it's deprecated, or is it still useful ?

**Comment by gregorylegarec** [comment]
No problem, I closed it because it have now conflicts and it's maybe too old.

The main purpose was to have Claudy in monlogis. I am looking if it's possible to reopen it and fix conflicts.

**Comment by gregorylegarec** [comment]
Conflicts fixed 👍

**Comment by jacquarg** [comment]
Done, thanks !

**Pull request merged**
